[package]
name = "test_utils"
version = "0.1.0"
authors = ["Filipe Rainho <filipenrainho@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempfile = "3.2.0"
anyhow = "1"
